---
- name: 1. Recolectar datos de todos los servidores
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Ejecutar check-update en el servidor
      ansible.builtin.command: dnf check-update
      register: update_check
      failed_when: update_check.rc > 100
      changed_when: false

    - name: Procesar información del host
      ansible.builtin.set_fact:
        # Filtra líneas que no sean paquetes (como avisos de expiración de metadata)
        clean_packages: "{{ update_check.stdout_lines | select('match','^[a-zA-Z0-9]') | list }}"
        ip_addr: "{{ ansible_default_ipv4.address | default('N/A') }}"
        fecha_ejecucion: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

    - name: Calcular métricas del host
      ansible.builtin.set_fact:
        p_count: "{{ clean_packages | length | int }}"
        status_name: >-
          {% if (clean_packages | length | int) > 9 %}CRITICAL
          {% elif (clean_packages | length | int) > 5 %}WARNING
          {% else %}OK{% endif %}

- name: 2. Generar reporte único y enviar por Office 365
  hosts: localhost
  gather_facts: no
  vars:
    # --- CONFIGURACIÓN REAL PARA OFFICE 365 ---
    smtp_host: "smtp.office365.com"           # Servidor de Microsoft
    smtp_port: 587                           # Puerto estándar TLS
    smtp_user: "tu-correo@tu-empresa.com"    # REEMPLAZAR: Tu correo remitente
    smtp_pass: "tu-contraseña-o-token"       # REEMPLAZAR: Tu App Password
    destinatario: "quien-recibe@dominio.com" # REEMPLAZAR: Correo de destino
    
    # --- AJUSTES DE ALINEACIÓN DE TABLA ---
    col1: 20
    col2: 18
    col3: 10
    col4: 10

  tasks:
    - name: Construir la tabla consolidada
      ansible.builtin.set_fact:
        tabla_final: |
          REPORTE DIARIO DE ACTUALIZACIONES PENDIENTES
          FECHA DE REVISIÓN: {{ hostvars[groups['all'][0]]['fecha_ejecucion'] | default('N/A') }}
          {{ "=" * 65 }}
          
          {{ "SERVIDOR".ljust(col1) }} | {{ "IP".ljust(col2) }} | {{ "UPDATES".ljust(col3) }} | {{ "ESTADO".ljust(col4) }}
          {{ "-" * 65 }}
          {% for host in groups['all'] %}
          {{ host.ljust(col1) }} | {{ hostvars[host]['ip_addr'].ljust(col2) }} | {{ (hostvars[host]['p_count'] | default(0) | string).ljust(col3) }} | {{ hostvars[host]['status_name'] | default('UNKNOWN').ljust(col4) }}
          {% endfor %}
          {{ "-" * 65 }}
          
          Nota: Este es un correo automático generado por AWX.

    - name: Enviar correo único de Office 365
      community.general.mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user }}"
        password: "{{ smtp_pass }}"
        to: "{{ destinatario }}"
        from: "{{ smtp_user }}"
        subject: "Reporte Consolidado de Actualizaciones - {{ ansible_date_time.date }}"
        body: "{{ tabla_final }}"
        secure: starttls
      delegate_to: localhost

    - name: Mostrar reporte en consola (Stdout)
      ansible.builtin.debug:
        msg: "{{ tabla_final }}"
