---
- name: Verificar actualizaciones pendientes
  hosts: all
  become: yes


  tasks:

  - name: Revisar paquetes disponibles
    ansible.builtin.command: dnf check-update
    register: update _check
    ignore_errors: yes

  - name: Mostrar resultado
    ansible.builtin.debug:
    var: update_check.stdout_lines
