---
- name: Auditoría de Actualizaciones Pendientes
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Ejecutar check-update
      ansible.builtin.command: dnf check-update
      register: update_check
      failed_when: update_check.rc > 100
      changed_when: false

    - name: Procesar información
      ansible.builtin.set_fact:
        # Limpiamos la lista para ignorar la línea de 'Last metadata expiration'
        clean_packages: "{{ update_check.stdout_lines | select('match','^[a-zA-Z0-9]') | list }}"
        ip_addr: "{{ ansible_default_ipv4.address | default('N/A') }}"

    - name: Definir métricas y colores
      ansible.builtin.set_fact:
        p_count: "{{ clean_packages | length | int }}"
        # Usamos nombres de estado simples para no romper la alineación
        status_name: >-
          {% if (clean_packages | length | int) > 9 %}CRITICAL
          {% elif (clean_packages | length | int) > 5 %}WARNING
          {% else %}OK{% endif %}

- name: Reporte Final en Tabla
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "MOSTRAR TABLA FINAL"
      ansible.builtin.debug:
        msg: |
          
          {{ "%-20s | %-15s | %-10s | %-10s" | format("SERVIDOR", "IP", "UPDATES", "ESTADO") }}
          {{ "-" * 65 }}
          {% for host in groups['all'] %}
          {{ "%-20s | %-15s | %-10s | %-10s" | format(host, hostvars[host]['ip_addr'], hostvars[host]['p_count'], hostvars[host]['status_name']) }}
          {% endfor %}
          {{ "-" * 65 }}
