---
- name: Obtener número de actualizaciones pendientes
  hosts: all
  become: yes
  gather_facts: no

  tasks:

    - name: Ejecutar dnf check-update
      ansible.builtin.command: dnf check-update
      register: update_check
      failed_when: update_check.rc > 100
      changed_when: false

    - name: Contar paquetes pendientes
      ansible.builtin.set_fact:
        pending_updates: "{{ update_check.stdout_lines | select('match','^[a-zA-Z0-9]') | list | length }}"

- name: Mostrar resumen consolidado
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Construir resumen
      ansible.builtin.debug:
        msg: |
          ===== RESUMEN GENERAL DE ACTUALIZACIONES =====
          {% for host in groups['all'] %}
          {{ host }} : {{ hostvars[host]['pending_updates'] | default('N/A') }} updates
          {% endfor %}
          ==============================================
