---
- name: Obtener número de actualizaciones pendientes
  hosts: all
  become: yes
  gather_facts: no

  tasks:

    - name: Ejecutar dnf check-update
      ansible.builtin.command: dnf check-update
      register: update_check
      failed_when: update_check.rc > 100
      changed_when: false

    - name: Contar paquetes pendientes
      ansible.builtin.set_fact:
        pending_updates: "{{ update_check.stdout_lines | select('match','^[a-zA-Z0-9]') | list | length }}"

    - name: Determinar estado del servidor
      ansible.builtin.set_fact:
        update_status: >-
          {% if pending_updates | int == 0 %}
          OK
          {% elif pending_updates | int <= 5 %}
          WARNING
          {% else %}
          CRITICAL
          {% endif %}

- name: Mostrar resumen consolidado
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Mostrar resumen general
      ansible.builtin.debug:
        msg: |
          ===== RESUMEN GENERAL DE ACTUALIZACIONES =====
          {% for host in groups['all'] %}
          {{ host }} : {{ hostvars[host]['pending_updates'] | default('N/A') }} updates ({{ hostvars[host]['update_status'] | default('UNKNOWN') }})
          {% endfor %}
          ==============================================
# --- AGREGA ESTA TAREA AQUÍ ---
    - name: Listado detallado de actualizaciones
      debug:
        msg: "{{ dnf_result.stdout_lines }}"
      when: dnf_result.stdout != ""

    - name: Contar paquetes pendientes
      set_fact:
        update_count: "{{ dnf_result.stdout_lines | length }}"# --- AGREGA ESTA TAREA AQUÍ ---
    - name: Listado detallado de actualizaciones
      debug:
        msg: "{{ dnf_result.stdout_lines }}"
      when: dnf_result.stdout != ""

    - name: Contar paquetes pendientes
      set_fact:
        update_count: "{{ dnf_result.stdout_lines | length }}"
