---
- name: 1. Recolectar datos de todos los servidores
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Ejecutar check-update
      command: dnf check-update
      register: update_check
      failed_when: update_check.rc > 100
      changed_when: false

    - name: Procesar informacion del host
      set_fact:
        clean_packages: "{{ update_check.stdout_lines | select('match','^[a-zA-Z0-9]') | list }}"
        ip_addr: "{{ ansible_default_ipv4.address | default('N/A') }}"
        fecha_ejecucion: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

    - name: Calcular metricas
      set_fact:
        p_count: "{{ clean_packages | length | int }}"
        status_name: >-
          {% if (clean_packages | length | int) > 9 %}CRITICAL
          {% elif (clean_packages | length | int) > 5 %}WARNING
          {% else %}OK{% endif %}

- name: 2. Reporte y Envio Office 365
  hosts: localhost
  gather_facts: no
  vars:
    # --- CONFIGURACION REAL ---
    smtp_host: "smtp.office365.com"
    smtp_port: 587
    smtp_user: "gdl.foxconnit@fii-na.com"    # REEMPLAZAR
    smtp_pass: "Cuentageneric4!"       # REEMPLAZAR
    destinatario: "juan.uribe@fii-na.com" # REEMPLAZAR
    
    col1: 20
    col2: 18
    col3: 10
    col4: 10

  tasks:
    - name: Construir tabla
      set_fact:
        tabla_final: |
          REPORTE DIARIO DE ACTUALIZACIONES
          FECHA: {{ hostvars[groups['all'][0]]['fecha_ejecucion'] | default('N/A') }}
          {{ "=" * 65 }}
          {{ "SERVIDOR".ljust(col1) }} | {{ "IP".ljust(col2) }} | {{ "UPDATES".ljust(col3) }} | {{ "ESTADO".ljust(col4) }}
          {{ "-" * 65 }}
          {% for host in groups['all'] %}
          {{ host.ljust(col1) }} | {{ hostvars[host]['ip_addr'].ljust(col2) }} | {{ (hostvars[host]['p_count'] | default(0) | string).ljust(col3) }} | {{ hostvars[host]['status_name'] | default('UNKNOWN').ljust(col4) }}
          {% endfor %}
          {{ "-" * 65 }}

    - name: Enviar correo unico
      # Usamos el nombre corto del modulo para maxima compatibilidad
      mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user }}"
        password: "{{ smtp_pass }}"
        to: "{{ destinatario }}"
        from: "{{ smtp_user }}"
        subject: "Reporte Actualizaciones - {{ lookup('pipe', 'date +%Y-%m-%d') }}"
        body: "{{ tabla_final }}"
        secure: starttls
      delegate_to: localhost
