---
- name: 1. Recolectar datos de todos los servidores
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Ejecutar check-update
      command: dnf check-update
      register: update_check
      failed_when: update_check.rc > 100
      changed_when: false

    - name: Procesar informacion del host
      set_fact:
        clean_packages: "{{ update_check.stdout_lines | select('match','^[a-zA-Z0-9]') | list }}"
        ip_addr: "{{ ansible_default_ipv4.address | default('N/A') }}"
        fecha_ejecucion: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

    - name: Calcular metricas
      set_fact:
        p_count: "{{ clean_packages | length | int }}"
        status_name: >-
          {% if (clean_packages | length | int) > 9 %}CRITICAL
          {% elif (clean_packages | length | int) > 5 %}WARNING
          {% else %}OK{% endif %}

- name: 2. Reporte y Envio via CURL (Office 365)
  hosts: localhost
  gather_facts: no
  vars:
    # --- DATOS OFFICE 365 ---
    smtp_server: "smtp.office365.com"
    smtp_user: "gdl.foxcoonit@fii-na.com"    # REEMPLAZAR
    smtp_pass: "Cuentageneric4!"       # REEMPLAZAR
    destinatario: "juan.uribe@fii-na.com" # REEMPLAZAR
    
  tasks:
    - name: Construir cuerpo del mensaje
      set_fact:
        reporte_body: |
          REPORTE DIARIO DE ACTUALIZACIONES
          FECHA: {{ hostvars[groups['all'][0]]['fecha_ejecucion'] | default('N/A') }}
          =================================================================
          SERVIDOR             | IP              | UPDATES    | ESTADO    
          -----------------------------------------------------------------
          {% for host in groups['all'] %}
          {{ "%-20s | %-15s | %-10s | %-10s" | format(host, hostvars[host]['ip_addr'], hostvars[host]['p_count'], hostvars[host]['status_name']) }}
          {% endfor %}
          -----------------------------------------------------------------

    - name: Enviar correo usando CURL
      shell: |
        cat <<EOF > /tmp/mail_data.txt
        Subject: Reporte Actualizaciones AWX
        From: {{ smtp_user }}
        To: {{ destinatario }}

        {{ reporte_body }}
        EOF

        curl --url 'smtp://{{ smtp_server }}:587' \
             --ssl-reqd \
             --mail-from '{{ smtp_user }}' \
             --mail-rcpt '{{ destinatario }}' \
             --user '{{ smtp_user }}:{{ smtp_pass }}' \
             --upload-file /tmp/mail_data.txt
      args:
        executable: /bin/bash
      delegate_to: localhost

    - name: Limpiar temporal
      file:
        path: /tmp/mail_data.txt
        state: absent
      delegate_to: localhost
