---
- name: Auditoría de Actualizaciones Pendientes
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Ejecutar check-update
      ansible.builtin.command: dnf check-update
      register: update_check
      failed_when: update_check.rc > 100
      changed_when: false

    - name: Procesar información
      ansible.builtin.set_fact:
        clean_packages: "{{ update_check.stdout_lines | select('match','^[a-zA-Z0-9]') | list }}"
        ip_addr: "{{ ansible_default_ipv4.address | default('N/A') }}"

    - name: Definir métricas
      ansible.builtin.set_fact:
        p_count: "{{ clean_packages | length | int }}"
        status_name: >-
          {% if (clean_packages | length | int) > 9 %}CRITICAL
          {% elif (clean_packages | length | int) > 5 %}WARNING
          {% else %}OK{% endif %}

- name: Reporte Final en Tabla
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "REPORTE DE ACTUALIZACIONES"
      vars:
        col1: 20
        col2: 20
        col3: 12
        col4: 10
      # Usamos pause con prompt para que AWX muestre el texto sin formato JSON
      ansible.builtin.pause:
        seconds: 1
        prompt: |
          
          {{ "SERVIDOR".ljust(col1) }} | {{ "IP".ljust(col2) }} | {{ "UPDATES".ljust(col3) }} | {{ "ESTADO".ljust(col4) }}
          {{ "-" * (col1 + col2 + col3 + col4 + 9) }}
          {% for host in groups['all'] %}
          {{ host.ljust(col1) }} | {{ hostvars[host]['ip_addr'].ljust(col2) }} | {{ (hostvars[host]['p_count'] | string).ljust(col3) }} | {{ hostvars[host]['status_name'].ljust(col4) }}
          {% endfor %}
          {{ "-" * (col1 + col2 + col3 + col4 + 9) }}
