---
- name: 1. Recolectar datos de todos los servidores
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Ejecutar check-update
      command: dnf check-update
      register: update_check
      failed_when: update_check.rc > 100
      changed_when: false

    - name: Procesar información
      set_fact:
        clean_packages: "{{ update_check.stdout_lines | select('match','^[a-zA-Z0-9]') | list }}"
        ip_addr: "{{ ansible_default_ipv4.address | default('N/A') }}"
        fecha_ejecucion: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

    - name: Definir métricas
      set_fact:
        p_count: "{{ clean_packages | length | int }}"
        status_name: >-
          {% if (clean_packages | length | int) > 9 %}CRITICAL
          {% elif (clean_packages | length | int) > 5 %}WARNING
          {% else %}OK{% endif %}

- name: 2. Reporte Final en Tabla
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "REPORTE DE ACTUALIZACIONES"
      pause:
        seconds: 1
        prompt: |
          
          FECHA DE REVISIÓN: {{ hostvars[groups['all'][0]]['fecha_ejecucion'] | default('N/A') }}
          -----------------------------------------------------------------
          SERVIDOR             | IP              | UPDATES    | ESTADO    
          -----------------------------------------------------------------
          {% for host in groups['all'] %}
          {{ host }} | {{ hostvars[host]['ip_addr'] }} | {{ hostvars[host]['p_count'] }} | {{ hostvars[host]['status_name'] }}
          {% endfor %}
          -----------------------------------------------------------------
